<a href="https://colab.research.google.com/github/KhushiChaudhary-cyber/python_programs/blob/main/dataframe_classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#setting path
path='/content/employee_dataset_5000.xlsx'
df=pd.read_excel(path)

In [35]:
#printing first 15 records
print("printing first 15 records")
df.head(15)

printing first 15 records

    EmpID EmpName DeptID DeptName   Salary
0     647    Anuj     D3  Finance  21264.0
1     450    Anuj     D4    Sales      0.0
2     994    Ravi     D2       IT      0.0
3     745    Amit     D3  Finance      0.0
4     657   Mohan     D2       IT  74969.0
5     518    Riya     D1       HR      0.0
6     596    Amit     D3  Finance  81450.0
7     172    Neha     D1       HR  53546.0
8     635    Neha     D1       HR  95882.0
9     819    Anuj     D4    Sales  50743.0
10    228    Riya     D4    Sales  86372.0
11    574    Anuj      0        0  24089.0
12    205    Amit     D1       HR  83920.0
13    629    Ravi     D2       IT  79262.0
14    427    Anuj     D3  Finance  23638.0

In [34]:
#displaying last 14 records
df.tail(14)

      EmpID EmpName DeptID DeptName   Salary
4986    506   Karan     D1       HR      0.0
4987    430   Mohan     D1       HR  81596.0
4988    411   Mohan     D1       HR      0.0
4989    366    Anuj     D2       IT      0.0
4990    339    Sita      0        0      0.0
4991    642    Sita      0        0      0.0
4992    813    Riya     D2       IT  67304.0
4993    642    Ravi     D3  Finance  97693.0
4994    315       0     D2       IT  28317.0
4995    557    Neha     D2       IT  40201.0
4996    616   Mohan     D2       IT      0.0
4997    572    Riya     D4    Sales  97422.0
4998    896   Mohan     D4    Sales      0.0
4999    880   Karan     D1       HR      0.0

In [15]:
#summary of dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EmpID     5000 non-null   int64
 1   EmpName   5000 non-null   object
 2   DeptID    5000 non-null   object
 3   DeptName  5000 non-null   object
 4   Salary    5000 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 195.4+ KB

In [16]:
#statistical summary
df.describe()

             EmpID        Salary
count  5000.000000   5000.000000
mean    550.958600  29941.591400
std     258.290749  33948.503359
min     100.000000      0.000000
25%     329.750000      0.000000
50%     554.000000  20218.000000
75%     768.000000  59818.750000
max     999.000000  99910.000000

In [17]:
#column names
df.columns

Index(['EmpID', 'EmpName', 'DeptID', 'DeptName', 'Salary'], dtype='object')

In [18]:
#find duplicated values
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996     True
4997    False
4998    False
4999     True
Length: 5000, dtype: bool

In [22]:
#remove duplicates
df.drop_duplicates()

      EmpID EmpName DeptID DeptName   Salary
0       647    Anuj     D3  Finance  21264.0
1       450    Anuj     D4    Sales      0.0
2       994    Ravi     D2       IT      0.0
3       745    Amit     D3  Finance      0.0
4       657   Mohan     D2       IT  74969.0
...     ...     ...    ...      ...      ...
4993    642    Ravi     D3  Finance  97693.0
4994    315       0     D2       IT  28317.0
4995    557    Neha     D2       IT  40201.0
4997    572    Riya     D4    Sales  97422.0
4998    896   Mohan     D4    Sales      0.0

[4438 rows x 5 columns]

In [23]:
#detect missing values
df.isnull()

      EmpID  EmpName  DeptID  DeptName  Salary
0     False    False   False     False   False
1     False    False   False     False   False
2     False    False   False     False   False
3     False    False   False     False   False
4     False    False   False     False   False
...     ...      ...     ...       ...     ...
4995  False    False   False     False   False
4996  False    False   False     False   False
4997  False    False   False     False   False
4998  False    False   False     False   False
4999  False    False   False     False   False

[5000 rows x 5 columns]

In [24]:
#values thatr are not missing
df.notnull()

      EmpID  EmpName  DeptID  DeptName  Salary
0      True     True    True      True    True
1      True     True    True      True    True
2      True     True    True      True    True
3      True     True    True      True    True
4      True     True    True      True    True
...     ...      ...     ...       ...     ...
4995   True     True    True      True    True
4996   True     True    True      True    True
4997   True     True    True      True    True
4998   True     True    True      True    True
4999   True     True    True      True    True

[5000 rows x 5 columns]

In [29]:
# identify and count missing values within a DataFrame
df.isnull().sum()

EmpID       0
EmpName     0
DeptID      0
DeptName    0
Salary      0
dtype: int64

In [32]:
# Fill missing values
df.fillna(0, inplace=True)

In [31]:
#displaying dataframe
print(df)

      EmpID EmpName DeptID DeptName   Salary
0       647    Anuj     D3  Finance  21264.0
1       450    Anuj     D4    Sales      0.0
2       994    Ravi     D2       IT      0.0
3       745    Amit     D3  Finance      0.0
4       657   Mohan     D2       IT  74969.0
...     ...     ...    ...      ...      ...
4995    557    Neha     D2       IT  40201.0
4996    616   Mohan     D2       IT      0.0
4997    572    Riya     D4    Sales  97422.0
4998    896   Mohan     D4    Sales      0.0
4999    880   Karan     D1       HR      0.0

[5000 rows x 5 columns]

In [12]:
print(df)

      EmpID EmpName DeptID DeptName   Salary
0       647    Anuj     D3  Finance  21264.0
1       450    Anuj     D4    Sales      0.0
2       994    Ravi     D2       IT      0.0
3       745    Amit     D3  Finance      0.0
4       657   Mohan     D2       IT  74969.0
...     ...     ...    ...      ...      ...
4995    557    Neha     D2       IT  40201.0
4996    616   Mohan     D2       IT      0.0
4997    572    Riya     D4    Sales  97422.0
4998    896   Mohan     D4    Sales      0.0
4999    880   Karan     D1       HR      0.0

[5000 rows x 5 columns]